name: Hello World CI
on: workflow_dispatch
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repository
        uses: actions/checkout@v6
      
      - name: run shell commands
        run: |
          echo "git clone success..."
          ls -lrtha
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: run shell commands
        run: |
          java -version
          mvn -version
      - name: Build with Maven
        run: |
           mvn clean install
           ls -lrth target/
      - name: Upload WAR/JAR artifact
        uses: actions/upload-artifact@v4
        with:
            name: maigolab-hello-artifact
            path: target/*.war
  testing:
    runs-on: ubuntu-latest
    needs: checkout-repo
    steps:
      - name: git checkout repository
        uses: actions/checkout@v6      
      - name: run shell commands
        run: |
          echo "git clone success..."
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
           mvn test
  deploy:
    needs: testing
    runs-on: self-hosted
    steps:
                  
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
           name: maigolab-hello-artifact
           path: ./artifact          
      - name: Deploy WAR
        run: |
          sudo rm -rf /opt/tomcat/webapps/*.war
          sudo rm -rf /opt/tomcat/webapps/*/
          sudo cp ./artifact/*.war /opt/tomcat/webapps/
          sudo systemctl restart tomcat
            