name: Hello World CI
on: workflow_dispatch
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repository
        uses: actions/checkout@v6
      
      - name: run shell commands
        run: |
          echo "git clone success..."
          ls -lrtha
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: run shell commands
        run: |
          java -version
          mvn -version
      - name: Build with Maven
        run: |
           mvn clean install
           ls -lrth target/
    